feat: fix_layout_for_mobile
lcnem/telescope pull request #175
Opened 2021-10-15 14:12 UTC by taro04

作成途中ですが、確認のためPR作成します。
![20211015_大文字化](https://user-images.githubusercontent.com/75844498/137501004-abc5aee5-8f53-4238-8ef9-d4de7893e073.png)
![20211015_-6桁](https://user-images.githubusercontent.com/75844498/137501009-6fe50cc9-29c3-46b3-9503-677acccf772b.png)
少数点６桁化は、htmlの{{　}}内でNumber( )が使えなかったので、自作の関数を定義しました。
ご確認お願い致します。問題なければ他にも展開します。

2021-10-18 04:29 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/home/distribution/distribution.component.html
> +      <span class="column-value">{{ pool.amount | number:'1.0-6' }}</span>
@taro04 
カスタムな関数を作成してそれを使わずとも、このようにAngularのpipeの機能を使うとシンプルに同様のことが実現できると思うので、こちらの書き方の方が適しているかなという印象を持ちました。

ここではサンプルとして、以下設定で書きましたが、桁数いくつにすべきか等の書き方は若干迷う部分もあって、適宜設定調整してみてください。(ホームページに表示されているコンポーネント関連で、pipe number等の書き方を使って修正したほうが良いところは他にもあると思うので、適宜修正トライしてみてください。)

- 整数部は必ず一桁表示(1.0-6の1 ... 0.***みたいな数字の0が省略されない?)
- 少数部は、整数等で少数部の桁が無い場合未表示(1.0-6の0)
- 少数部は、最大6桁まで表示(1.0-6の6)

pipe numberの書き方の説明は以下記事がわかりやすかったので参考にしてみてください。
https://qiita.com/xKxAxKx/items/7ff964d20c573a547c85

非同期なデータやObservableなデータによく使うasync pipe以外にも、Angularではデフォルトで日時や数字等の扱いに関して便利なpipeがデフォルトで用意されているので、日時や数字やパーセントや通貨等をちょっとした表示上の変換を加えて使う場合等には、pipeを頭の片隅に置いておくとよいと思います。カスタムなpipeを定義して使うことも可能です。

詳細は以下公式の説明を確認してみてください。
https://angular.jp/guide/pipes

2021-10-19 01:40 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
xxsのブレークポイントをカスタムで設定する必要性が薄いように感じました。
一旦は以前カスタムで設定したxs(600px)やtailwindでデフォルトで用意されているsm(640px)を使うようにする修正方針で進めるのはいかがでしょう？
(なお、以前カスタムで設定したxsの600pxにはこだわりはおそらくないと思うので、どこかでtailwindデフォルトのsm(640px)にあわせていく等できるとよさそうと思っていますが、それは別のプルリクでやったほうが良いかなと思っていて、一応notionにタスクとして書き出しておきましたので状況だけご承知おきください。)

2021-10-19 01:40 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/home/home.component.html
> +        <span class="ml-2 break-all text-sm xxs:text-base">
xxsという新しいブレークポイントを設定せずとも、tailwindでデフォルトで用意されているsm(640px)を使う等でも十分かなという気がしています。あるいは以前600pxでカスタムで設定追加して頂いたxsをいったん使っておくとか。もしそれで不都合があったら教えてください。

なお、以前、xsというカスタムで設定追加して頂いた600pxのブレークポイントは、tailwindでデフォルトで用意されているブレークポイントを使うよう、全体的に修正したほうが良いかもしれません。(おそらく、UIの600pxにさほど深い理由はなく、Angular Flex-Layoutが600pxでブレークポイントを提供していたからに過ぎないと思っていて、tailwind化したなら、600pxではなくsmの640pxに変えたり、600pxをハードコードしているTypeScriptの箇所等も修正しておいた方が自然かなと思っていて、そのような修正をどこかでやっておいた方がよいかなと思っているというイメージです。)
ただ、sx→sm(tailwindでデフォルトで用意されているブレークポイント)に修正する件は、別のプルリクで今後修正をお願いしたいと思っているので、今回はxsはそのままでもよいです。
念のため、背景と、今後お願いさせてもらおうと思っているということについてはご承知おきください。

2021-10-19 01:40 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/home/home.component.html
> +        <span class="ml-2 break-all text-sm xxs:text-base">
xxsでなく、xsやsmでよいのではと感じました。

2021-10-19 01:40 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/home/home.component.html
> +        <span class="ml-2 break-all text-sm xxs:text-base">
xxsでなく、xsやsmでよいのではと感じました。

2021-10-19 01:40 UTC, YasunoriMATSUOKA commented on tailwind.config.js
> +        xxs: '361px'
xxsの必要性に疑問を感じました。
もし不都合なければいったんxsを使っておいてはどうでしょうか。
(あと、今回のプルリクではそのままでよいと思いますが、どこかで別途、tailwindのデフォルトのブレークポイントに全体的に切り替える修正をしましょう。)

2021-10-19 14:23 UTC, taro04 commented
一旦進捗報告でcommitします。引き続き作業します。青の部分は修正が必要と思われる個所です。
![20211019_blocks_chk](https://user-images.githubusercontent.com/75844498/137929489-5715847b-e22f-44c5-8574-3abc9f516c8a.png)
![20211019_tx_chk](https://user-images.githubusercontent.com/75844498/137929512-61d2784d-b616-4fa1-9708-e419f85845f8.png)
![20211019_key要修正](https://user-images.githubusercontent.com/75844498/137929531-19864a5c-97df-419e-bd2d-4e0c783e240b.png)

2021-10-21 00:40 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/keys/create/create.component.html
> +  <!--<br />-->
コメントアウトでなく、消してしまってOKです。こちらで修正しておきます。

2021-10-21 00:43 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/txs/tx/tx.component.css
> -}
他のコンポーネントだと、同様のクラスが残ったままになっているところが、改めてみると気になりました。
notionにタスクとして記載しておいたので、このプルリクとは別のタスクとして、tailwindの書き方に揃えておくのが良いかなと思いました。
他にも、classをtailwindの枠組みの外で書いてあるところは、少しずつtailwindの枠組みの中の書き方に修正していきたいですね。Angular MaterialにデフォルトであたっているCSS等を調整するために書いているCSS等は、tailwindの枠組みの書き方を当てはめるのは無理なものもあるかもしれませんが、そうでないものは、少しずつtailwindの枠組みの書き方に修正していきましょう。

2021-10-21 00:53 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/txs/tx/tx.component.html
> +        z' }}</span>
フォーマッターが自動的にこのようなstyleにしているのかもしれませんが、さすがにdateの書式設定の途中で改行されているのはイマイチと感じたので、ここで改行しておいたほうが良いのでは？という形に変えておこうと思います。もしこちらのフォーマッターが効いていないだけだったらすみません。

2021-10-21 01:24 UTC, YasunoriMATSUOKA approved these changes
LGTM

2021-10-21 01:24 UTC, merged