feat: add key backup dialog
lcnem/telescope pull request #189
Opened 2021-10-26 13:38 UTC by taro04

作成途中ですが、進捗報告のためPR作成します。
現在ダイアログcomponentとserviceを追加し、ダイアログ閉じるまでアカウント作成の処理を中断するところまで、作成しました。
引き続き、ニーモニックを保存する機能の追加と、保存したか確認するように実装を進めます。
![image](https://user-images.githubusercontent.com/75844498/138889733-a6b9072c-21d5-49b7-9947-1c149b995031.png)

2021-11-01 02:24 UTC, YasunoriMATSUOKA commented
@taro04 cc: @KimuraYu45z @Senna46 

全体的な方針として、以下の制御は必要だと感じました。これらは実装しましょう。

> 当初は、ダウンロードしないと②に進めない、チェック通らないと③に進めないような制限をかけていたのですが、例えばダイアログ開きなおしたときなと毎回DLする必要はないと思って制限を外しています。ご確認お願い致します。

以下修正の際の指針として参考にしてみてください。

1. 全体的に、問題があったときに問題があったことをユーザーに伝えたり、次の操作に進められないように制御する実装が無いと感じました。
  1. 例えばニーモニックの何単語目の単語を入力させてチェックするところで、チェック結果がNGでもユーザーが次のステップに進めて、Submitボタンを押せてしまうのは良くないと思います。
  2. 具体的にはボタンの活性化・非活性化をdisabledプロパティを適切にセットして、そもそも問題がある入力値や状態でユーザーが次に進めなくしたり、問題がある値でユーザーが次へ進むボタンをクリックせざるを得ないパターンが残った場合は結果的に操作がうまくいかなかった場合にうまくいかなかった旨ユーザーにSnackBarやDialogで伝えてあげる実装が必要かなと感じました。
2. ファイル名は、key_idが入っているとユーザーに優しいかなと感じました。

2021-11-01 03:27 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z @Senna46 
気になったところにコメントつけてみたので、そのあたりも参考にしながら、問題があった場合にユーザーが次に進めないような制御を加えることと、問題があったときにユーザーが問題があったことを認識できるような通知を加えることを意識して、修正取り組んでみてください。

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/models/keys/key-backup-dialog.service.ts
> +  async open(mnemonic: string, privatekey: string): Promise<boolean | undefined> {
@taro04 cc: @KimuraYu45z @Senna46 
この関数が単なるbooleanではなく、以下のような型を返り値として得られるようにすると、このダイアログサービスの呼び出し元コンポーネントでもっと柔軟な条件判定や実装が可能ではないかと感じました。
(複数の状態を持っていると思うので、それらを個別に取得しておいたほうが、柔軟で正確な制御ができるはずでそれほど手間ではないはずという所感です。)

```ts
{
  saved?: boolean;
  checked?: boolean;
}
```

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/keys/create/create.component.ts
> +    const saved: boolean | undefined = await this.keyBackupDialog.open(this.mnemonic, $event.privateKey);
@taro04 cc: @KimuraYu45z @Senna46 
コメント頂いた内容の意味合いはちょっと良くわからなかったのですが...、

savedとcheckedという二つのクラス変数を用意しておき、いったんここでresultのような値で、以下の型のような結果を受け取って、

```ts
{
  saved?: boolean;
  checked?: boolean;
}
```

以下のようなイメージでクラス変数でDialog内のバックアップファイルダウンロード実行・未実行の状態や、ニーモニックのチェック結果の可否状態の結果を受け取ってやっておけば、以降のロジックを柔軟に制御できるのでは？と思いました。

```ts
this.saved = result.saved;
this.checked = result.checked;
```

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/keys/create/create.component.ts
> +    }
@taro04 cc: @KimuraYu45z @Senna46 
このif文のelseに相当する場合に、ユーザーに問題があったことをスナックバーやダイアログで伝えられるような実装があったほうが良いと思いました。

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.html
> +</mat-stepper>
@taro04 cc: @KimuraYu45z @Senna46 
ボタンの色、表示・非表示や、活性化・非活性化等、状況に応じて制御を工夫してみてください。

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
> +    this.matDialogRef.close(this.checked);
@taro04 cc: @KimuraYu45z @Senna46 
例えば以下のように、単なる1個のbooleanな値を返すのではなく、ファイルダウンロードしたか否かのsavedと、ニーモニックの確認がOKかNGかのcheckedそれぞれの値を独立して返してあげたほうが、柔軟で正確な制御ができるのでは？と思いました。

```suggestion
    this.matDialogRef.close({ saved: this.saved, checked: this.checked });
```

2021-11-01 03:27 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
> +  private mnemonicArray = this.data.mnemonic.split(/\s/)
@taro04 cc: @KimuraYu45z @Senna46 
クラス変数の宣言はClassの定義の冒頭にまとめましょう

Angularの公式のコーディングスタイルガイドのリンクを共有しておきます。
関数の宣言の順序等は必ずしも公式の順序にマッチしていない実装もこのプロジェクト内には正直あります(ngOnInitをはじめとするAngularのライフサイクルメソッドとパブリックなメソッドの前後関係はあまり意識していなくて、正直、違いがある気がするのです)が、クラス変数の宣言位置がここにあるのは、かなりミスリーディングな書き方に見えたので、この行の書き方については修正したほうが良いと思いました。
https://angular.jp/guide/styleguide#style-05-14

2021-11-01 12:08 UTC, taro04 commented on projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
> +  private mnemonicArray = this.data.mnemonic.split(/\s/)
すみません、デバック中にとりあえずこの位置に置いたので、上段にまとめました。

2021-11-02 09:04 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
最後に以下の修正を加え、松岡としてはこれでレビューOKの認識です。
もし何か気になったところあれば、コメントくださると助かります。

- デザイン(ボタンの色でNextをクリックできるかどうかをわかりやすく、配置位置、上下ボタン間にスペース追加等の変更等)
- ロジック(チェック結果NGの際にNextで次に進めるパターンをふさぐ修正、新たにkeyがcreateされたり、新しいmnemonicが入力された時にバックアップ状況のクラス変数をリセットする修正の追加)
- 不要な箇所の削除
- アラートメッセージにより詳細な警告の文章を追加

動作イメージは以下の通りです。

成功時のパターン
![telescope-key-backup-dialog-success-20211102](https://user-images.githubusercontent.com/55148923/139816168-a43076eb-947e-40b3-ab3a-466c1ece63da.gif)

ダイアログ途中で抜ける等の失敗のパターン
![telescope-key-backup-dialog-failure-20211102](https://user-images.githubusercontent.com/55148923/139816219-7f7e6da7-d06a-47c1-b106-fd65871190b0.gif)

cc: @taro04 
一旦、これでマージしてしまおうと思っていますが、もし何か気づいたことあったら、後でnotionに書くか、Issue作成しておいてもらえると助かります。
修正内容の意図等、ざっくり把握しておいてもらえると助かります。

2021-11-02 09:05 UTC, KimuraYu45z approved these changes
かなりよくなりましたね。

2021-11-02 09:07 UTC, YasunoriMATSUOKA approved these changes

2021-11-02 09:07 UTC, merged