feat: debag account info page
lcnem/telescope pull request #197
Opened 2021-11-09 13:10 UTC by taro04

質問と確認のため、PR作成します。（デバック用の回路も多数のこっています。）

■事象
存在しないアドレスを入力すると、非表示であるべき「Validator Rewards」以下のmat-cardが表示される。

![image](https://user-images.githubusercontent.com/75844498/140929769-664291c7-b7f8-4491-b371-c609d9c0ba73.png)

2021-11-09 13:21 UTC, taro04 commented on projects/main/src/app/views/accounts/account/distribution/distribution.component.html
> +<ng-container *ngIf="commision?.commission?.commission?.[0] === undefined || null ; then empty; else exist">
このcommision?.commission?.commission?.[0]に何が入っているか確認すると、
型はobjectのnullが入っているようです。
![image](https://user-images.githubusercontent.com/75844498/140930317-2b249f3a-5091-481a-b1b2-08e07439ce36.png)

これはnull型とは違うものですよね？
またこの*ngIfでObjectのnullを検知する方法は何かありますか？

2021-11-10 09:47 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/accounts/account/distribution/distribution.component.html
> +<ng-container *ngIf="commision?.commission?.commission?.[0] === undefined || null ; then empty; else exist">
@taro04 cc: @KimuraYu45z 
質問については申し訳ないですが自分ではよくわかりませんでした。
ただ、そもそも、この件、自分だったら、viewsディレクトリ配下のコンポーネントで対処するのではなく、pagesディレクトリ配下のデータ取得箇所でのエラーハンドリングを適切に行う方向性で修正トライするかなと思いました。(そして、ngIfにはもっとシンプルな条件式を書くと思います。アドレスが不正であった場合は、commision$自体にデータが流れていかないようにするとか。そうすれば子コンポーネントのロジックはcommision自体がnullとかundefinedで判断できるのではないでしょうか？)

pagesディレクトリ配下のデータ取得処理の以下ファイルの中の、accAddress$やvalAddress$が、エラーによって適切な値が流れてこない状態を、filterとかcatchErrorとかのrxjsオペレーターを使って、うまくエラーハンドリングするという方向性で考えてはいかがでしょう？ご検討ください。
projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts

2021-11-10 09:48 UTC, YasunoriMATSUOKA requested changes
@taro04 cc: @KimuraYu45z 
修正方針コメントしてみたので参考にしてみてください。

2021-11-10 13:47 UTC, taro04 commented
`*ngIf="(commision?.commission?.commission?.length || 0) > 0`
proposal.componentを参考にngIfの条件を修正したところ意図した動作になりました。

今回、存在しないアドレスと、残高が無いアドレスで、返す値に差異があった（nullか、[]か）ためngIfの条件から漏れるパターンがありましたが、配列の要素が存在することを確認する上記の方法なら問題ないかなと思っています。

残高無いアドレスは空の配列、存在しないアドレスはnullを返すことは、考えとしては問題ないと思っていて、追加のエラー処理は無くても良いかなと思っています。

`*ngIf="(commision?.commission?.commission?.length || 0) > 0`
エラー処理は変更せず、この条件で修正しても問題ないでしょうか？
（pushできなかったので、コメントのみ失礼します。）

2021-11-11 02:30 UTC, YasunoriMATSUOKA commented
@taro04
アドレスの文字列から、accAddressに変換するところでエラーが発生していて、そのエラーを適切にハンドリングできていない状況だと思うので、そこを放置するのは(せっかくデバッグとして目をつけてくださった今の機会を逃すのは)もったいないかなと感じました。

エラーハンドリング等の修正提案を以下プルリクに作成してみたので、レビューして、問題無ければマージして進めてみてください。(デバッグは甘めなので、すみませんが慎重にレビューしてもらえると助かります。)

https://github.com/lcnem/telescope/pull/200

条件判定はコメントくださったやり方で問題ありませんが、エラーハンドリングはこの機会にやっておきましょう。

cc: @KimuraYu45z 
もし、上記違和感あれば、フォローくださると助かります。
よろしくお願いします。

2021-11-15 01:35 UTC, YasunoriMATSUOKA approved these changes
LGTM

2021-11-15 01:36 UTC, merged