fix: slash information in account info page
lcnem/telescope pull request #205
Opened 2021-11-12 13:22 UTC by taro04

確認と進捗報告のためPR作成します。

// Todo: '2' must be fixed to latest block height  →　完了。

//and add pagination support!　→　こちらがイメージついていません。

このページのslashの部分にページネーションを設定するという認識でしょうか？その場合、キーは何になるのでしょうか？
![image](https://user-images.githubusercontent.com/75844498/141473240-1208dd9c-6636-49a5-8dd7-298ecd553927.png)

あと、txsページでslashingを選択するとtx数が０なのはslashingが発生していないということですよね。どのようにデバックすればよいかアドバイスいただけると幸いです。

2021-11-12 13:27 UTC, taro04 commented on projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts
> +  slashes$: Observable<CosmosDistributionV1beta1QueryValidatorSlashesResponse | undefined>;
catchErrorをセットし、undefinedを返すため、型に追加しています。

2021-11-15 01:32 UTC, YasunoriMATSUOKA commented
@taro04 
> このページのslashの部分にページネーションを設定するという認識でしょうか？その場合、キーは何になるのでしょう？
はい。その認識です。以下リンクファイルのトランザクション一覧ページと同様に、データ取得し、表示できるよう実装を試みてください。(≒トランザクション一覧ページを参考にしてください。)なお、トランザクション一覧ページでは、paginationKeyにはundefinedがセットされているようです。
https://github.com/lcnem/telescope/blob/main/projects/main/src/app/pages/txs/txs.component.ts

> txsページでslashing確認すると０なので、まだslashingが発生していないと思っています。
> 簡単に発生させることができるのであれば、デバック用にいくつかデータがあると幸いです。
slashingを発生させるには、いずれか一つのノードを(確か10分以上くらいだったか？)停止させてみるのが一番早いと思います。説明するまでもないかもしれませんが、ノードを停止させるのは、`cd ~/jpyx`, `docker-compose down`で、ノードを再起動させるには、同じディレクトリで`docker-compose up -d`を実行すればOKです。各ノード上で`jpyxd keys list`コマンドを実行して表示されるアカウントのうち、mainという名前のアカウントがvalidatorのアカウントなので、停止させたノードのmainアカウントにslashingが発生すると思います。そのような形でデバッグトライしてみてください。dのノードを止めてトライしてみてください。その際、ノード止めるとき、ノード再開するときは、Slackにて一言コメントお願いします。

cc: @KimuraYu45z 
slashingに関しては、松岡もあまり自信がなく、もし違和感あったらフォローくださると助かります。
よろしくお願いします。

2021-11-15 01:32 UTC, YasunoriMATSUOKA requested changes
@taro04 
コメントしたので確認と対応お願いします。

2021-11-15 01:32 UTC, YasunoriMATSUOKA commented on projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts
>      );
この一連の実装なのですが、おそらく、catchErrorオペレーターで例外がキャッチされると、Observableなデータの流れが途切れてしまうのではないかと懸念しています。APIを叩いている箇所に直接エラーハンドリングを書いておく等の対応が本来は必要であるように思いました。ただ、この件は、他にも同様の問題を抱えた箇所が多数あると思うので、いったん保留にして、別途全体的に1ページずつ修正に取り組んだ方がよいかもしれません。一応念のため記載しておきます。

2021-11-15 15:01 UTC, taro04 commented
実装は出来たと思うのですが、ノード止めてみてもSlashのトランザクションが発生しませんでした。なので動作確認はできていないです。お手数ですが、Slashingの発生条件をご確認いただけないでしょうか？何卒よろしくお願いいたします。

2021-11-15 15:07 UTC, taro04 commented on projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts
>      );
この部分ですが直前のエラー処理追加のPRで、まさに上記のとおり松岡さんで修正いただいていました。このブランチ切る際に正しくpullができていなかったです。申し訳ありません。

2021-11-17 02:14 UTC, YasunoriMATSUOKA commented
@taro04 cc: @KimuraYu45z 
もし、メインブランチとのコンフリクト解消してくださった箇所に確信が持てていない状況であるなら、別ブランチとして作り直してくださってもかまいません。
そこの進め方はお任せします。
Slashingに関しては、申し訳ありませんが、松岡も確信が持てていない部分が多いので、引き続き調査しつつ、進めてもらえると助かります。

2021-11-17 09:54 UTC, taro04 commented
コメントありがとうございます。一旦クローズして別ブランチで再作成します。

2021-11-17 09:54 UTC, closed without merging