feat: add account delete dialog
lcnem/telescope pull request #208
Opened 2021-11-16 13:30 UTC by taro04

製作途中ですが、進捗報告かねPR作成します。作成したアカウント機能の追加タスクです。
・/keys/:key_idページの上端右端にDeleteボタンを追加。
　（このボタンはあえてゴミ箱のアイコンだけにしています。さすがに分かりにくいでしょうか？
　　そうであればCreateと同じようにflatボタン＋iconに修正します。）
・アカウント削除ダイアログ追加。
・idの判定と判定結果のスナックバー表示追加
![image](https://user-images.githubusercontent.com/75844498/141993235-72d243e8-7ca4-4a7f-8a4c-14750eb11b9e.png)
明日以降実際のアカウント削除の実装をします。

2021-11-17 02:10 UTC, YasunoriMATSUOKA requested changes
詳細は未確認ですが、現時点で気になったことを以下にコメント残しておきます。実装の参考にしてくださればと思います。

1. 普通あまり実行しないであろう危険度の高い機能を実行するためのボタンは、赤色等の警告であることが直感的にわかるような色にするのが好ましいと感じました。Angular Materialのデフォルトのカラーテーマだとwarnがそれに相当すると思うので、それを使用するのが自然かなと思いました。
2. ダイアログ内の文字か枠の色等でも警告色を使うくらい、本当にkeyを消していいの？という点を警告したほうが良いと思いました。
2. ゴミ箱アイコンはわかりにくいかもしれませんが、ダイアログの中で何を行う操作かもう少し丁寧に説明があれば問題にはならないかなと感じました。個人的にはユーザーに値を手動でインプットさせるダイアログの中で「秘密鍵本当に消していい？バックアップできていなかったら資産にアクセスできなくなっちゃうよ？それでもよかったらkey_idインプットして次に進んでね」的な説明を入れておき、ユーザーに考えさせる構成にしておくのがよいかなあと思いました。

2021-11-17 10:01 UTC, taro04 commented
警告色の件、承知しました。ダイアログ重ねるなど、立ち止まらせる仕組みと、説明の追加を行います。

2021-11-19 12:44 UTC, taro04 commented
機能は実装完了しました。以下のとおり確認しています。
１点、２段目のダイアログでmat-flat-buttonの色指定ができていません。
<Form>の中でないとダメかと思って試してみたのですが、
解決せずです。何かご存じでしたらご教示いただきたくお願いします。

https://user-images.githubusercontent.com/75844498/142624336-12499999-4fbe-4c92-9f50-17d7b3d0ab18.mp4

2021-11-22 03:48 UTC, YasunoriMATSUOKA requested changes
@taro04 
2点、コメントしておきました。こちらの修正に問題はないか確認＆追加で必要な修正をお願いします。

2021-11-22 03:48 UTC, YasunoriMATSUOKA commented on projects/main/src/app/app.module.ts
> +    KeyDeleteConfirmDialogModule,
@taro04 cc: @KimuraYu45z 
KeyDeleteConfirmDialogComponentのみ、buttonのwarnの色が反映されていなかった件、おそらく、この行のKeyDeleteConfirmDialogModuleのimportが無かったことが原因だと思います。修正加えておいたので確認してみてください。

ぱっと見ただけではイマイチ原因がピンときませんでしたが、ググってみて、解決の糸口にたどりつきました。
キーワードは angular mat-dialog button color といった感じで、以下のstack overflowとGitHub のIssueが参考になりました。
https://stackoverflow.com/questions/61214229/mat-button-style-not-applying-in-dialog-component
https://github.com/angular/components/issues/18705

ただ、冷静に考えてみると、
- 最上位のapp.module.tsでグローバルに対象コンポーネントを使用可能にしておくためのimportをしておくか、
- routingに応じて表示されるコンポーネントに対応したmoduleにimportしておくかのいずれかの対応が必要で、
KeyDeleteConfirmDialogComponentだけ、それが漏れていたというただそれだけのシンプルな状況だったということにも思えました。自分もこのあたり時々混乱してしまうのですが、この機会に改めて何をどうimportしておく必要があるか、自分なりに整理してみることをお勧めします。

2021-11-22 03:48 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/keys/key/key.component.html
> +      <mat-icon color="accent">delete</mat-icon>
@taro04 cc: @KimuraYu45z 
このボタンはkeyをdeleteする機能に進むボタンなので、そういった危険なステップを次に進めるボタンは、全てcolorをwarnで統一しておくのが良いと思いました。

2021-11-22 13:06 UTC, taro04 commented on projects/main/src/app/app.module.ts
> +    KeyDeleteConfirmDialogModule,
確認ありがとうございます。しょうもないミスですみません。Dialog自体は動いていたので、importは問題ないものだと思いこんでいました。。。@NgModule、declarations、exportsや、以下の”違い”が分かっていないので整理します。
![image](https://user-images.githubusercontent.com/75844498/142866802-6eca0cc8-ec05-44cc-b01d-13432dcc29f6.png)

2021-11-22 13:34 UTC, taro04 commented
アイコンとボタン色修正しました。配置など合わせて修正しています。
![image](https://user-images.githubusercontent.com/75844498/142870433-d5f61f06-77c6-4cbf-b340-0ffbce0b824b.png)
お手数ですが、ご確認お願い致します。

2021-11-26 04:56 UTC, YasunoriMATSUOKA commented
@taro04 
最後のダイアログが、ユーザーが何も考えずに不注意でEnterを押した場合、ユーザーの意図に反して削除が実行されてしまうリスクがあると思ったので、OKとCancelのボタンを入れ替えました。
https://github.com/lcnem/telescope/pull/208/commits/fbae988a9a7eb64937069da78c98a0e9841691fd

また、警告的なニュアンスをもう少し高めてもよいかと思った文言を赤枠で囲んだり、インプットボックスの幅をダイアログと揃えたり、メッセージを若干変更したり、lint修正したりしました。

2021-11-26 05:10 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/26932)
マージしておきます。

2021-11-26 05:10 UTC, merged