feat: tx_response.code
lcnem/telescope pull request #225
Opened 2021-11-22 06:05 UTC by Senna46

close #207 
#222 も一部解決

bank.application.serviceにて、返ってきたtx_response.codeによってエラーを吐く仕様に変更。
そのため。間違ったDenomなどの場合にtx_response.raw_logをSnackBarに表示しています。

> HTML上でプルダウンリストにする
denomの選択について本PRでは対応していませんが、もし必要であればコメントお願いします。
'invalid coin'のエラーは出るので不要な気もします。

@YasunoriMATSUOKA 確認お願いします。

![invalidcoin](https://user-images.githubusercontent.com/29295263/142808660-6ca7bbeb-5b6c-4553-87b3-69fe63ac1cf8.png)

2021-11-22 06:09 UTC, YasunoriMATSUOKA commented
@Senna46 
間違ったDenomをinputできないよう、プルダウンの対応もあわせてお願いします。

2021-11-22 06:19 UTC, YasunoriMATSUOKA commented
@Senna46 
以下Issueについてもこのプルリクで対応できそうであればお願いします。
https://github.com/lcnem/telescope/issues/224

2021-11-22 06:20 UTC, YasunoriMATSUOKA requested changes
このページの機能に関連するIssueをこのプルリクで修正してしまいましょう。お願いします。

2021-11-22 07:47 UTC, Senna46 commented
Denomをプルダウンリストで選択するように変更
プルダウンリストの中身はprojects/main/src/app/views/cosmos/bank/send/send.component.tsに記載しています。

#224 の同じDenomは複数欄入力させない修正についてはHTML側でのバリデーションが難しそうだったので、projects/main/src/app/models/cosmos/bank.application.service.tsのInvalid Coinエラーで良い気がしています。

send.component.ts側でAlertもやってみましたが、出るタイミングがInvalid Coinエラーとほとんど同じなのと、例えばBTCとuBTCを同じDenomとしないといけないので、色々と冗長になると思いました。

#223についてはチェックボックスを暫定的に廃止しています。もし、確認ダイアログを実装する場合、AuctionやCDPでもつけた方がいいと思うのでまとめてやった方がいいと思います。

2021-11-22 07:52 UTC, YasunoriMATSUOKA commented
@Senna46 

> #224 の同じDenomは複数欄入力させない修正についてはHTML側でのバリデーションが難しそうだったので、projects/main/src/app/models/cosmos/bank.application.service.tsのInvalid Coinエラーで良い気がしています。

`projects/main/src/app/views/cosmos/bank/send/send.component.ts`のaddAmount, removeAmountメソッドの中に、プルダウンの選択肢から抜いたり、追加したりする処理を書いたり、同じDenomがFormにInputされないようなチェック処理をかけば、そもそもFormをそういう状態にしないという形で、さほど手間をかけずに実現できませんか？

トライしてみてください。

2021-11-22 07:55 UTC, YasunoriMATSUOKA commented
@Senna46 

> send.component.ts側でAlertもやってみましたが、出るタイミングがInvalid Coinエラーとほとんど同じなのと、例えばBTCとuBTCを同じDenomとしないといけないので、色々と冗長になると思いました。

BTCとuBTCを同じdenomとするのは、今必ずしもやらなくてよいと思います。ubtc, ujsmn, jpyxの3種類のdenomのみの前提で対応進めてください。

2021-11-22 08:02 UTC, Senna46 commented
@YasunoriMATSUOKA AddAmount, RemoveAmountは値を入れていない状態でもできるのでここで選択肢を増やしたり減らしたりするのは無意味な実装になってしまいます。
なのでHTMLのForm側でやるしかないですが、Form内での配列要素ごとのバリデーションのやり方がわからないのでこれ以上進められません。

2021-11-22 08:14 UTC, YasunoriMATSUOKA requested changes
@Senna46 
追加された修正点について気になったところにコメント残しました。
確認お願いします。

2021-11-22 08:14 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/bank/send/send.component.ts
> +  ];
@Senna46 cc: @KimuraYu45z 
変数名や、そもそもその項目ここで必要？といった点に違和感を感じたので、以下の例を参考に修正してください。(詳細なデバッグしたわけではないので、他パラメーター名との重複があった場合は適切な名前を検討してください。)

例
tokens -> denomOptions
Denom -> denomOptionInterface
value -> denom
viewValue -> description ... そもそもこの項目必要？

2021-11-22 08:17 UTC, YasunoriMATSUOKA commented
> @YasunoriMATSUOKA AddAmount, RemoveAmountは値を入れていない状態でもできるのでここで選択肢を増やしたり減らしたりするのは無意味な実装になってしまいます。

入っている値を確認して対応すれば、さほど手間をかけることなく、無意味でない実装が可能と思います。

> なのでHTMLのForm側でやるしかないですが、Form内での配列要素ごとのバリデーションのやり方がわからないのでこれ以上進められません。

いいえ、上記の通り、可能ではないでしょうか。検討してください。

2021-11-22 08:31 UTC, YasunoriMATSUOKA commented
@Senna46 
以下の件、こちらで少し動かしてみて、言わんとすることを理解しました。確かに、今のフォームのままで、addAmountとremoveAmountだけに処理を追加する形では不可能そうです。失礼しました。
https://github.com/lcnem/telescope/pull/225#issuecomment-975240537

その場合、例えば、フォームの形式自体を変えて、保有しているトークンの項目のみあらかじめ全てAmount: 0で表示させておき、Sendする際に、Amountが0のトークンをデータから除くような形で実装するのはどうでしょうか？

トライしてみてください。

2021-11-24 10:52 UTC, Senna46 commented
@YasunoriMATSUOKA 
https://github.com/lcnem/telescope/pull/225/commits/2d7cf3725da77f72f2ca5a5bf4b0ab0f5e72e652
にて、所有しているDenomをすべて表示にしてみましたが、
projects/main/src/app/views/cosmos/bank/send/send.component.html Line30の
amount[i]が`Object is possibly 'null' or 'undefined'.`のエラーが解消できません。

また、0amountの列を排除するのもやり方がわからず詰まっています。

お手すきのときで良いのでアドバイスいただけないでしょうか？

2021-11-24 11:05 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/bank/send/send.component.html
> +          *ngIf="amount[i] !== null || undefined; then enable; else disable"
@Senna46 
そこまで詳細を見れていませんが、この行のamountが、nullやundefinedの場合、コメント頂いたようなエラーになるように感じたので、この行の条件判定を行うための前段階の条件判定として、amount自体がnullやundefinedでない場合といったngIfやng-templateやng-containerが必要なのではないかと思いました。
このあたりに着目して、修正トライしてみてください。
今日は時間も遅いので、これくらいにして、もし必要あれば、明日相談しましょう。
最悪テストネットローンチに間に合わなくてもOKという想定で、自分なりに考えながら取り組んでみてください。

2021-11-24 11:06 UTC, KimuraYu45z commented on projects/main/src/app/views/cosmos/bank/send/send.component.html
> +          *ngIf="amount[i] !== null || undefined; then enable; else disable"
`amount?.[i]`がだめなら`amount && amount[i]`とか

2021-11-24 11:10 UTC, YasunoriMATSUOKA commented on projects/main/src/app/views/cosmos/bank/send/send.component.ts
> +  ];
これ、改めて見たら、denomOptionInterfaceではなく、DenomOptionInterfaceが適切でしたね。すみません。

2021-11-24 11:16 UTC, YasunoriMATSUOKA commented
@Senna46 
0amountのデータを排除するのは、配列に対して使える、filter関数を使う等して、amountが'0'等のfalsyな配列の要素は落として、truelyな要素だけ残す等の方法が自然かなと思いました。(良く考えてみると、amountという名前で設定されている変数が、実際には配列だと思うので、amountsとかの方が変数名としても適切かもしれない等といったことも思いました。)
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2021-11-25 07:23 UTC, Senna46 commented
@YasunoriMATSUOKA CC: @KimuraYu45z 
ICoinの配列をamountsに変更し、amount && amount[i]のやり方でnull or undefinedの問題を対処しました。
所有しているDenomのみを初期値0で与え、onSubmit発火時に0以下のDenomを排除するよう実装しています。

すべて0の場合は`Error has occured: Error: : invalid coins`を吐きます。

要件は満たせたと思いますので、レビューお願いします。

![send1](https://user-images.githubusercontent.com/29295263/143397249-3dead230-5d32-44d4-9342-add9c32d381f.PNG)
![send2](https://user-images.githubusercontent.com/29295263/143397264-8b1fb00a-9944-4f01-9b47-783b23b19fce.PNG)

2021-11-26 07:42 UTC, YasunoriMATSUOKA commented
@KimuraYu45z cc: @Senna46 
松岡としては、一部修正を加えて、これでLGTMという所感なのですが、変数名(msgSendのプロパティに合わせてamountにすべき？それとも意味合い的にわかりやすい(と松岡は思う)coinsにすべき？)といったところや、エラーハンドリングでcodeだけでなく、raw_logもチェックすべき？といったところについては、)賛否両論ありそうな修正になっているような気がしています。
お手数ですが、木村さんの所感を聞かせてもらえないでしょうか。
(以降、このエラーハンドリングを標準的な対応として、他のトランザクション送信のServiceも修正していくことになると思うので、ある程度筋の良い実装にこのタイミングで整えておけるといいなあと思っているという背景があります。)

修正内容は以下の通りです。

- anyではなく、型が効くような形に修正しました。
- それに伴いtxhashがundefinedになりうる実装となったため、その場合の例外処理を追加しました。
- 変数名をいくつか修正しました。

最後に松岡が加えた追加の変更は以下2コミットです。

https://github.com/lcnem/telescope/pull/225/commits/ecdd964e65ec24fec847c7749d7cc220bd37f969
https://github.com/lcnem/telescope/pull/225/commits/9ea079faf0c3513dfc9632254c60c602a360a3e3

2021-11-26 08:02 UTC, KimuraYu45z commented
あーそうですね、msgsend型にあわせてamountにしといていい気がしますね。

2021-11-26 08:02 UTC, KimuraYu45z commented
raw logはjson文字列が入ってると思うのですがかわりにlogをつかう認識であってますか？

2021-11-26 08:06 UTC, YasunoriMATSUOKA commented
承知しました。amountに戻しておきますね。

もう一点念のため確認させてください。
エラーハンドリングのロジックについては、codeだけをチェックする形で違和感ないでしょうか？
それとも元の実装の通り、codeが0ではない＆raw_logに何らかの値が入っていることをチェックする形の方が違和感ないでしょうか？
元の実装だと、codeが0ではないパターンで、raw_logがundefinedの場合正常と判断されると思ったので、raw_logはエラーハンドリングのロジックからは除いたほうが良いかなと思ったのですが、いかがでしょうか？

2021-11-26 08:06 UTC, YasunoriMATSUOKA commented
あ、すれ違った

2021-11-26 08:16 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
例えばtxhashを指定してAPIを叩くと以下のようなjsonが得られるのですが、tx_responseの中を見ると、raw_logはjson文字列が入っていて、logはjsonが入っているという状況でした。

エラーハンドリングのロジックとして「code!==0なら失敗でそうでないなら成功」だと松岡は思っていたのですが、もしそうではなく「code!==0かつraw_log!==undefinedなら失敗でそうでないなら成功」という認識が正しいのであれば、もとに戻す必要があるという認識で、そこがどちらなのか迷っているという感じです。(どっちでも大差ないかもしれないのですが、一応、この後、他のServiceにも同様の修正を横展開することになりそうなので、この機会に明確に整理しておきたいと考えているという感じです。)

```json
{
  "tx": {
    "body": {
      "messages": [
        {
          "@type": "/cosmos.bank.v1beta1.MsgSend",
          "from_address": "jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r",
          "to_address": "jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99",
          "amount": [
            {
              "denom": "ubtc",
              "amount": "10"
            }
          ]
        }
      ],
      "memo": "",
      "timeout_height": "0",
      "extension_options": [
      ],
      "non_critical_extension_options": [
      ]
    },
    "auth_info": {
      "signer_infos": [
        {
          "public_key": {
            "@type": "/cosmos.crypto.secp256k1.PubKey",
            "key": "AtAAEoTPGPjscUg/XoEyuogRMuuvdipm+8X9RKcdoUFV"
          },
          "mode_info": {
            "single": {
              "mode": "SIGN_MODE_DIRECT"
            }
          },
          "sequence": "0"
        }
      ],
      "fee": {
        "amount": [
        ],
        "gas_limit": "200000",
        "payer": "",
        "granter": ""
      }
    },
    "signatures": [
      "GUGuxkKbHMqjJr5l1No0TkG4+pXDbpEQCDgX8nweND9IZjcsrLmQjuu63oN9TkrzhTLCIiM8ybkrPc89t9eOPQ=="
    ]
  },
  "tx_response": {
    "height": "48540",
    "txhash": "565FD670E7A7C01DA2F89482AEB6A681336826830C5FDA9735F6A895289065B8",
    "codespace": "",
    "code": 0,
    "data": "0A060A0473656E64",
    "raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"sender\",\"value\":\"jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99\"},{\"key\":\"sender\",\"value\":\"jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r\"},{\"key\":\"amount\",\"value\":\"10ubtc\"}]}]}]",
    "logs": [
      {
        "msg_index": 0,
        "log": "",
        "events": [
          {
            "type": "message",
            "attributes": [
              {
                "key": "action",
                "value": "send"
              },
              {
                "key": "sender",
                "value": "jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r"
              },
              {
                "key": "module",
                "value": "bank"
              }
            ]
          },
          {
            "type": "transfer",
            "attributes": [
              {
                "key": "recipient",
                "value": "jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99"
              },
              {
                "key": "sender",
                "value": "jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r"
              },
              {
                "key": "amount",
                "value": "10ubtc"
              }
            ]
          }
        ]
      }
    ],
    "info": "",
    "gas_wanted": "200000",
    "gas_used": "56460",
    "tx": {
      "@type": "/cosmos.tx.v1beta1.Tx",
      "body": {
        "messages": [
          {
            "@type": "/cosmos.bank.v1beta1.MsgSend",
            "from_address": "jpyx1403shzhm7m6svr26my6qqjd4jlexjeztqgjp6r",
            "to_address": "jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99",
            "amount": [
              {
                "denom": "ubtc",
                "amount": "10"
              }
            ]
          }
        ],
        "memo": "",
        "timeout_height": "0",
        "extension_options": [
        ],
        "non_critical_extension_options": [
        ]
      },
      "auth_info": {
        "signer_infos": [
          {
            "public_key": {
              "@type": "/cosmos.crypto.secp256k1.PubKey",
              "key": "AtAAEoTPGPjscUg/XoEyuogRMuuvdipm+8X9RKcdoUFV"
            },
            "mode_info": {
              "single": {
                "mode": "SIGN_MODE_DIRECT"
              }
            },
            "sequence": "0"
          }
        ],
        "fee": {
          "amount": [
          ],
          "gas_limit": "200000",
          "payer": "",
          "granter": ""
        }
      },
      "signatures": [
        "GUGuxkKbHMqjJr5l1No0TkG4+pXDbpEQCDgX8nweND9IZjcsrLmQjuu63oN9TkrzhTLCIiM8ybkrPc89t9eOPQ=="
      ]
    },
    "timestamp": "2021-11-25T09:55:29Z"
  }
}
```

2021-11-26 08:26 UTC, KimuraYu45z commented
code、2通りの認識にかんして、なにが根拠でこの推測をしたかとかありますか？

2021-11-26 08:41 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
code===0ならトランザクションが成功だろうと推測しているのは、例えばbank sendのトランザクションで失敗時には以下のようにcode===4のレスポンスが返ってきて、

```json
{
  "tx_response": {
    "height": "0",
    "txhash": "2D7F3DFE8AB83760BBE1B144945F41AA2BBABE5CFA835EF56922DBE3AC3DD74E",
    "codespace": "sdk",
    "code": 4,
    "data": "",
    "raw_log": "signature verification failed; please verify account number (28) and chain-id (jpyx-4-test): unauthorized",
    "logs": [
    ],
    "info": "",
    "gas_wanted": "200000",
    "gas_used": "30110",
    "tx": null,
    "timestamp": ""
  }
}
```

成功時には以下のようにcode===0のレスポンスが返ってきていることから判断しています。

```json
{
  "tx_response": {
    "height": "63805",
    "txhash": "EE0B31C35EAF28496C4E4771492F584367B3413FCE04F0977F01F45D110469BD",
    "codespace": "",
    "code": 0,
    "data": "0A060A0473656E64",
    "raw_log": "[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"sender\",\"value\":\"jpyx1y0w90lrkdfgrrsl7egk9uaa54azfakj5d0ss95\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99\"},{\"key\":\"sender\",\"value\":\"jpyx1y0w90lrkdfgrrsl7egk9uaa54azfakj5d0ss95\"},{\"key\":\"amount\",\"value\":\"1ubtc\"}]}]}]",
    "logs": [
      {
        "msg_index": 0,
        "log": "",
        "events": [
          {
            "type": "message",
            "attributes": [
              {
                "key": "action",
                "value": "send"
              },
              {
                "key": "sender",
                "value": "jpyx1y0w90lrkdfgrrsl7egk9uaa54azfakj5d0ss95"
              },
              {
                "key": "module",
                "value": "bank"
              }
            ]
          },
          {
            "type": "transfer",
            "attributes": [
              {
                "key": "recipient",
                "value": "jpyx1nxyujwckzwyg870gk9m9qzp9z2av00we6fks99"
              },
              {
                "key": "sender",
                "value": "jpyx1y0w90lrkdfgrrsl7egk9uaa54azfakj5d0ss95"
              },
              {
                "key": "amount",
                "value": "1ubtc"
              }
            ]
          }
        ]
      }
    ],
    "info": "",
    "gas_wanted": "200000",
    "gas_used": "50043",
    "tx": null,
    "timestamp": ""
  }
}
```

code!==0かつraw_log!==undefinedなら失敗という2個目の条件については、松岡としては確証はありません。(以前からそう実装されていたかどうかはちょっと記憶がさだかではないのですが、大村さん実装のプルリクのレビューで初めて松岡としてはそういう実装がなされていることに気づき、code!==0でraw_logがundefinedになっているパターンがもしあったら、エラーにも関わらず成功に判定してしまうのではという懸念を感じて少しだけ相談させてもらったのですが、そんなパターンはないのでは？という意見をもらい、さほど重要ではないかと思って、その際はそれでApproveさせてもらったという経緯があったように思います。)

2021-11-26 09:03 UTC, KimuraYu45z commented
なるほどですね
raw logはつかわずcode判定だけでいいと思いました。

2021-11-26 09:24 UTC, YasunoriMATSUOKA commented
@KimuraYu45z 
> raw logはつかわずcode判定だけでいいと思いました。

承知しました。その形で進めます。

2021-11-26 09:29 UTC, YasunoriMATSUOKA approved these changes
@Senna46 
対応ありがとうございました。こちらでマージしておきます。
LGTM
![LGTM](https://image.lgtmoon.dev/148266)

2021-11-26 09:29 UTC, merged