feat: daelete angular flex layout only from package.json
lcnem/telescope pull request #226
Opened 2021-11-23 10:47 UTC by taro04

[#94](https://github.com/lcnem/telescope/issues/94)
以下の手順でflex-layout削除しました。
１、package.jsonからflex-layout削除
２、node_modulesフォルダを削除
３，npm i 

[package-lock.jsonはnpmインストールした際の具体的なバージョンを保存するもので、人が編集するものではないとの記事
[https://qiita.com/sugurutakahashi12345/items/1f6bb7a372b8263500e5](https://qiita.com/sugurutakahashi12345/items/1f6bb7a372b8263500e5)

を見たので今回触っていませんが、package-lock.jsonの中にflex-layoutの文字が残っているのが気になりました。問題ないかご確認お願いしたいです。

表示について、ローカルとデブロイされているサイトを並べて確認し問題ないと思いました。
差異があったのは以下３点です。
①Transaction
![20211123_flexlayout1](https://user-images.githubusercontent.com/75844498/143009994-21712ddc-1d95-4260-bc56-b2873d62207e.png)
こちらはローカル側は問題ないと思いますが、デブロイされている方がメッセージタイプ”o”となっており別で調査が必要かと思います。

②Monitor
![20211123_flexlayout2](https://user-images.githubusercontent.com/75844498/143010027-19d25432-5ade-439a-b7cf-01270bfaa86f.png)
③JPYX
![20211123_flexlayout3](https://user-images.githubusercontent.com/75844498/143010039-59cd7c9a-828d-41be-b481-152f1fcb7122.png)
2、3はbotanyの範囲なのでこちらも同様にflex-layoutの削除が必要と考えます。
（telescopeのflex-layout削除手順の確認いただいたのち実施します。）

2021-11-25 10:37 UTC, taro04 commented
すみませんこちら、各Module.tsからも消す必要があると思うので、ＰＲ更新します。

2021-11-25 13:26 UTC, taro04 commented
残りtoolbar.moduleからも削除する必要がありますが、既存の[ngClass]でbreakpointによってCSSを切り替えている部分が、tailwindで実装できず、削除できていません。もう少しトライさせてください。

2021-11-26 08:51 UTC, YasunoriMATSUOKA commented
@taro04 
色々トライしてくださってありがとうございます。
Angular Flex-Layoutの書き方が残っているところは意外と網羅的に見つけにくいかもしれないので、一通りのファイルについて、注意深く探して頂き、削除前後の挙動の差や、デプロイされているバージョンとの表示結果の差等にも注意して、意図しないデグレができるだけ起こらないよう、慎重に進めてもらえると助かります。

2021-11-26 08:53 UTC, YasunoriMATSUOKA requested changes
作業に目途がついてレビューしてほしい状態になったら改めてお声かけください。

2021-11-26 14:27 UTC, taro04 commented
・改めて確認したところ、monitorにflex-layoutが残っていたので、修正しました。

・toolbar.tsで、flex-layoutの[ngClass]を使用して、toolbarのFormのCSSを切り替えていた箇所を
　tailwindで実装しました。微妙に表示が異なりますが、以下の理由で現状でレビューいただきたくお願いいたします。
![image](https://user-images.githubusercontent.com/75844498/143594356-6ccbd2bc-d4c1-4f42-b09c-69c36bdc23ae.png)

１，CSSでは小数点まで設定していたが、tailwindでは整数しか指定できない。
　[https://tailwindcss.com/docs/margin](https://tailwindcss.com/docs/margin)
２，tailwindのxs:が640px、ngClass.xsの切り替えが600pxなので、レスポンシブルでも微妙に漏れる範囲がある。
　（カスタムbreakpointを設定できるが、ここのために以前削除した600pxのカスタムbreakpointを復活させるか。）
３，tailwindのレスポンシブル表現、xs:がツールバーに対して機能してしない。
　（すみません。原因追及できてないです。）

お手数をおかけしますが、よろしくお願いいたします。

2021-11-29 00:52 UTC, YasunoriMATSUOKA requested changes
@taro04 

質問に対する回答を以下にコメントしました。
参考の上、修正お願いします。

- 600pxにこだわる必要は特にないと思うので、リンク https://tailwindcss.com/docs/breakpoints のsmの640pxに統一する方向で修正しましょう。(アプリ全体として640pxにそろっていれば特に問題はないのでは？と思っています。以前サイドナビ関連を修正したとき、そのような方針で修正したと思うので、今回もそれと揃える形で問題ないのでは？と思うのですが、もし何か問題あればご指摘ください。)
- xsが効かないのは、tailwindのデフォルトのbreakpointにxsというものは存在しないからではないでしょうか。(今はtailwindのデフォルトのbreakpointだけが使える状態になっており、仕様通りの挙動だと思います。気になる場合は`tailwind.config.js`を確認してください。)無理に600pxを維持する必要は特になく、smの640pxを使用すればよいのではと思います。(カスタムなbreakpointとしてxsという名前で600pxを追加することはできますが、600pxに特別なこだわりはないと思うので、smの640pxを使って修正してくださればよいのではないかと思いました。)

後は細かい指摘で恐縮ですが、(誤)レスポンシブル→(正)レスポンシブだと思いました。(レスポンシブデザインは英語表記でresponsive designだと思うのでこの機会に覚えておいてください。responsibleとは違う言葉ですね。)

2021-12-06 13:13 UTC, taro04 commented
toolbar.component.htmlをtailwindで置き換える際に、問題が２点あります。

１、breakpoint
　ヘッダーの高さは600pxで変わる（ngClassのxs）がtailwindはデフォルト最小設定が640px（sm）
　ヘッダーの高さを640pxで変わるように変更したいが、どこで設定されているか分からない。

２、margin-top
　CSSでは1.34375emが設定できたが、tailwindでは0.5em刻み。tailwind化するともっとも近い1.5remしか設定できない。
　
しかし２は、ヘッダーの検索フォームがよりヘッダーの最下部に近づいたので、1.5remの方がベターかと思います。（赤いライン）
https://user-images.githubusercontent.com/75844498/144851531-c99c1f91-a538-4903-b3e2-2ba295c39b30.mp4

したがって問題点は実質１のみだと考えます。
こちらについて設定を変更する箇所をご存じでしたらご教示いただきたくお願いいたします。

※：ご指摘の通り tailwindのbreakpointは xsではなく、smでした。ありがとうございます。
※：responsibleの意味は”責任ある”ですね。お恥ずかしい。。。

2021-12-07 02:49 UTC, YasunoriMATSUOKA commented
@taro04 

細かいところまで確認頂きありがとうございます！以下に所感を記載しました。私の所感としては最後に加えて頂いた修正でOKかなと思っています。Approveしておくので、問題無ければマージしておいてください。

> １、breakpoint
> 　ヘッダーの高さは600pxで変わるがtailwindはデフォルト最小設定が640px（sm）
> 　ヘッダーの高さを640pxで変わるように変更したいが、どこで設定されているか分からない。

確かにヘッダーの高さは600pxで変わるけれど、サイドナビは明示的に設定したtailwindのsm(640px)で変わるという点で違いがありますね...

推測ですがヘッダーの高さが600pxで変わるのは、Angular Materialのmat-toolbarの仕様なのではないでしょうか？
そこを設定しに行くこと自体は何か方法があるかもしれないとも思いますが、この挙動自体にあまり実害はないと思うので、現状の実装でよいのではないかと思いましたがいかがでしょう？

揃えられるならtailwindのsmの640pxに揃える方向が良いと過去の時点では考えていましたが、Angular Materialのデフォルトの挙動を書き換える設定してまではやらなくてよいかなという所感です。

> ２、margin-top
> 　CSSでは1.34375emが設定できたが、tailwindでは0.5em刻み。tailwind化するともっとも近い1.5remしか設定できない。

1.5remの設定で問題ないと思います。デザイン的にも違和感なければOKです。

言葉については、お互い間違えているところ等色々あったりすると思うので、お互いカジュアルに指摘しあえるといいですね。(お互い変に委縮したりせずすむよう、程よいバランスでうまく進めていけるとありがたいです。間違いを過度に恐れる必要はないのでそこは意識して頂けると助かります。)

2021-12-07 02:50 UTC, YasunoriMATSUOKA approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/74458)

2021-12-07 11:30 UTC, taro04 commented
コメントありがとうございます。私も、ヘッダーの高さが変わるのはAngular Materialのmat-toolbarの仕様（というかバグ？）だと思ってます。マージさせていただきます。
英語については、むしろご指摘ありがたいです！。特にコミットメッセージなど、かなり怪しいのもあると思いますが、ご指摘いただけると幸いです。

2021-12-07 11:31 UTC, merged