feat: delete last element divider
lcnem/telescope pull request #227
Opened 2021-11-23 12:15 UTC by taro04

[https://github.com/lcnem/telescope/issues/215](https://github.com/lcnem/telescope/issues/215)の修正です。

以下の記事を参考に実装しました。
[https://dev.classmethod.jp/articles/mat-divider-last-hidden/](https://dev.classmethod.jp/articles/mat-divider-last-hidden/)

レイアウト見てhome、Transaction詳細、Block詳細ページ以外のページはdividerが必要だと感じたので、
home、Transaction詳細、Block詳細ページのみ修正を行いました。
同様にhomeページ、Transactionのカードは、pagenationとの区別にdividerが必要だと思ったので
こちらも削除していません。

実装結果です。
![20211123_del_last_divider1](https://user-images.githubusercontent.com/75844498/143021597-53f49347-2a88-4205-8689-7f8c700332f9.png)

また、カードが連続している部分のレイアウトを見直しました。
![20211123_del_last_divider2](https://user-images.githubusercontent.com/75844498/143021593-20aa3302-3657-46c7-bb2f-d4fb09a0046e.png)

ご確認お願い致します。

2021-11-26 09:21 UTC, YasunoriMATSUOKA commented
@taro04 
ホームページにおいて、ブロック一覧は表の最下部のdividerを消しているのに対し、トランザクション一覧はdividerを残しているのは何か意図があってのことでしょうか？その点だけ少し違和感を感じました。それ以外は特に違和感ありません。念のため何か意図がある場合は教えてくださると助かります。(最後にそこだけ修正を元に戻している( https://github.com/lcnem/telescope/pull/227/commits/bf8f0d6450dacdf892cd70f97401248fba3491e3 )ように見えたので、何か意図がありそうに感じました。)

![image](https://user-images.githubusercontent.com/55148923/143556637-e0d69600-cfa0-4bd7-82de-260da715810a.png)

2021-11-26 09:22 UTC, YasunoriMATSUOKA requested changes
修正要望というより、確認のみです。→後で考えたら実質的には修正要望な気がしました。
統一されていればどちらでもOKかなと感じました。
https://github.com/lcnem/telescope/pull/227#issuecomment-979814551

2021-11-29 00:56 UTC, YasunoriMATSUOKA requested changes
@taro04 

コメント( https://github.com/lcnem/telescope/pull/227#issuecomment-979814551 )の件、ホームページで、ブロック一覧とトランザクション一覧の最終行のdivider表示しない・表示するの違いをあえて作っている理由が知りたいです。
もし特に理由がない場合は、揃えた方が自然だと思いました。
個人的にはどちらでもさほど違和感はないけれど、Issueの指摘としては、消す方向なのかな？と思いました。
もし何か理由がある場合は、理由を教えて頂けると助かります。
よろしくお願いします。

2021-12-06 11:35 UTC, taro04 commented
意図としては、Blocksは０のことは無いですが、Transactionは選択によっては０の場合があり、０の場合にdividerを消すとぬるっとした感じになるので、Txでは残していました。
![image](https://user-images.githubusercontent.com/75844498/144838734-2ac0e931-559a-4ad6-8f62-44b433515601.png)

と以前は思ったのですが、改めてみるとそこまで違和感もないので、削除します。

2021-12-07 02:18 UTC, YasunoriMATSUOKA reviewed
LGTM!
![LGTM](https://image.lgtmoon.dev/72923)

2021-12-07 02:19 UTC, YasunoriMATSUOKA approved these changes

2021-12-07 02:19 UTC, merged